baseurl = "/"
title = "reigo.eu"
author = "Reigo Hendrikson"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = "UA-113538088-1"
disqusShortname = "reigo"
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:slug/"

[params]
  sitename = "reigo.eu"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/ReigoHendrikson"
    weight = 3
[[menu.main]]
    name = "RWeekly"
    url = "https://rweekly.org"
    weight = 4
[[menu.main]]
    name = "R-bloggers"
    url = "https://www.r-bloggers.com/"
    weight = 5
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 6