baseurl = "/"
publishDir = "public"
title = "reigo.eu"
author = "Nan Xiao"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = "UA-113538088-1"
disqusShortname = "reigo"
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "reigo.eu"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rendrikson"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/ReigoHendrikson"
    weight = 3